# Generated by Django 4.2.11 on 2024-06-20 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_category_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
