# Generated by Django 4.2.11 on 2024-06-21 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingaddress",
            options={"verbose_name_plural": "Addresses"},
        ),
    ]
